image: python:3.7

stages:
  - lint
  - test
  - build
  - release

.code:
  only:
    changes:
      - src/**/*
      - tests/**/*
      - pyproject.toml
      - pytest.ini
      - tox.ini

before_script: 
  - pip install poetry
  - pip install tox 

lint:black:
  stage: lint
  extends: .code
  script: tox -e black

lint:flake8:
  stage: lint
  extends: .code
  script: tox -e flake8

test:python27:
  stage: test
  image: python:2.7
  script: 
    - tox -e py27

test:python35:
  stage: test
  image: python:3.5
  extends: .code
  script: 
    - tox -e py35

test:python36:
  stage: test
  image: python:3.6
  extends: .code
  script: 
    - tox -e py36

test:python37:
  stage: test
  extends: .code
  script: 
    - tox -e py37

test:python38:
  stage: test
  image: python:3.8
  extends: .code
  script: 
    - tox -e py38

build:package:
  stage: build
  script: tox -e build
  artifacts:
    paths:
      - dist
    expire_in: 1 week

release:pypi:
  stage: release
  script:
    - poetry publish -u $PYPI_USERNAME -p $PYPI_PASSWORD
  only:
    - tags
