---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
      - id: flake8
        exclude: tests
      - id: trailing-whitespace
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
